$(function(){
	$('.p,.u').hammer().on('tap',function(e){
		e.gesture.srcEvent.preventDefault();
		if(!$(this).hasClass('selected')){
			$('.p,.u').toggleClass('selected');
			$('.product,.order').toggleClass('hide');
		}
	});
});