<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  "COMMUNITY" => "社区",
  "naked Hub is a tribe of individuals who crave fulfilling work as part of a healthy life." => "已经是裸心社会员",
  "SPACES" => "空间",
  "Work in a naked space: beautiful design that brings nature indoors.Get all the facilities you need, with the extras that make coming to work fun." =>"在设计优美的裸心空间里工作，在室内也能亲近自然。工作需要的设施都为你准备好了，而且还有很多惊喜让你乐在其中。",
  "PERKS" => "会员优待",
  "Beyond the community and space,we sprinkle in some extra treats that make working naked fun." => "除了工作社区与工作空间，裸心社还有额外的小惊喜，让你对工作充满期待。",
  "FUN" => "会员福利",
  "naked Hub is a fresh take on work and play.Home to a diverse community of creatives, entrepreneurs and dreamers, these co-working hubs are a place to come together to learn, meet and collaborate with your peers." => "享受团队协作，却免受考勤限制。",
  "JOIN THE COMMUNITY" => "加入我们",
  "LOGIN" => "登录",
);
