<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  "BECOME A NAKEDHUB MEMBER" => "成为裸心社会员",
  "I'M ALREADY A NAKEHUB MEMBER" => "已经是裸心社会员",
  "THE COMMUNITY" => "社区",
  "NakeHub members are incredibly diverse,ranging from the startup,freelancer,and artist to the small business and large multinational.Got a question ?Ask the community." =>"NakeHub成员是令人难以置信的多样化，从启动，自由职业者和艺术家的小型企业和大型跨国企业有一个问题？问社区。"
);
